// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsqkwFTO2d5wGudmlq-X1FzYHFlq3TuVQ',
    appId: '1:917341559501:web:5ce0013004e47c1d1fa784',
    messagingSenderId: '917341559501',
    projectId: 'fir-30682',
    authDomain: 'fir-30682.firebaseapp.com',
    storageBucket: 'fir-30682.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsQL6fsnRG9Eu-hEgYfnvAufJlEpnLBSc',
    appId: '1:917341559501:android:59cee09a586bb1d61fa784',
    messagingSenderId: '917341559501',
    projectId: 'fir-30682',
    storageBucket: 'fir-30682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp6Y2UI_EtDryNvYIAfSzjvT-55qJ17BY',
    appId: '1:917341559501:ios:34a3f2e3a626e1e01fa784',
    messagingSenderId: '917341559501',
    projectId: 'fir-30682',
    storageBucket: 'fir-30682.appspot.com',
    iosBundleId: 'com.example.firebasetutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp6Y2UI_EtDryNvYIAfSzjvT-55qJ17BY',
    appId: '1:917341559501:ios:95365401c0fb56451fa784',
    messagingSenderId: '917341559501',
    projectId: 'fir-30682',
    storageBucket: 'fir-30682.appspot.com',
    iosBundleId: 'com.example.firebasetutorial.RunnerTests',
  );
}
